// POST request to example server
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "J",
  "password": "12345678",
  "firstName": "Jame",
  "lastName": "Smith",
  "birthDate": "2000-02-22"
}

###