// POST request to example server
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "J971",
  "password": "12345678",
  "firstName": "Jack",
  "lastName": "BoCon",
  "birthDate": "1997-02-22"
}

###